---
openresty_host_ssl_certificates:
  test:
    certificate:
      file: files/test.pem
    key:
      file: files/test.key

openresty_host_lua_scripts:
  test:
    directory: files/lua/test/
    dest: echo_header

openresty_host_sites_available:
  molecule:
    template: openresty-molecule-site.conf.j2
  disabled: |
    server {
      listen 127.0.0.1:8001;
      server_name localhost;

      location /molecule {
        add_header Content-Type text/plain;
        return 200 'ansible';
      }
    }
  lua_echo: |
    server {
      listen 127.0.0.1:8008;
      server_name localhost;

      location / {
        default_type text/plain;
        content_by_lua_block {
          local echo_header = require "echo_header.echo_header"
          echo_header.echo()
        }
      }
    }
  ssl: |
    server {
      listen 127.0.0.1:8443 ssl;
      server_name localhost;

      ssl_dhparam {{ openresty_ssl_dhparam_path }};
      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_certificate {{ openresty_ssl_certificate_directory }}/test.pem;
      ssl_certificate_key {{ openresty_ssl_certificate_directory }}/test.key;

      location / {
        default_type text/plain;
        return 200 'SSL';
      }
    }

openresty_host_sites_enabled:
  molecule: true
  disabled: false
  lua_echo: true
  ssl: true
