---
openresty_host_sites_available:
  molecule:
    template: openresty-molecule-site.conf.j2
  disabled: |
    server {
      listen 127.0.0.1:8001;
      server_name localhost;

      location /molecule {
        add_header Content-Type text/plain;
        return 200 'ansible';
      }
    }

openresty_sites_enabled:
  molecule: true
  disabled: false
